refactor/rng
emilioheinz/release-notes-generator pull request #11
Opened 2021-04-26 17:53 UTC by RigottiG

- [x] Added milestone as a filter

2021-04-26 18:25 UTC, emilioheinz requested changes

2021-04-26 18:25 UTC, emilioheinz commented on src/index.js
> +}
Cria uma pasta de factories e coloca esse cara la 😄

2021-04-26 18:27 UTC, opoze requested changes

2021-04-26 18:27 UTC, opoze commented on package.json
> +  "engines": {
Só isto daqui que me preocupou... não tenho certeza que estamos utilizando esta versão nas maquinas.

2021-04-26 18:39 UTC, emilioheinz commented on package.json
> +  "engines": {
Conferi e a principio está, só não está sendo forçado.

2021-04-26 18:41 UTC, opoze commented on package.json
> +  "engines": {
show

2021-04-26 18:41 UTC, opoze approved these changes

2021-04-26 19:35 UTC, emilioheinz requested changes

2021-04-26 19:35 UTC, emilioheinz commented on src/utils/index.js
> +module.exports = { byLabel, byMilestone, byRepository }
```suggestion
const filters = require('./filters')

module.exports = { filters }
```

2021-04-26 19:35 UTC, emilioheinz commented on src/utils/index.js
> +module.exports = { byLabel, byMilestone, byRepository }
Não esquece de mudar o uso tambem

2021-04-27 12:55 UTC, emilioheinz approved these changes

2021-04-27 12:56 UTC, merged