feat/sort-and-filters
emilioheinz/release-notes-generator pull request #8
Opened 2021-03-12 18:28 UTC by opoze

Changed to sorte with -s and filter by repository name.
Changed -c to required and don't use the first column.

Sem sort
node ./index.js -o ArezzoCo -p 112 -t token-c DONE

#474 Ajuste CTA da PDP de brinde
#676 Revisar fluxo de compra com cartão de crédito
#834 Corrigir picker no formulário de cartão de crédito no Samsung A10s
#562 Modal de atualização de versão recomendada e obrigatória
#697 Alterar campo do texto que é exibido na vitrine da home
Com Sort
node ./index.js -o ArezzoCo -p 112 -t token-c DONE -s

#252 Ajuste no componente de botão com seta
#375 [Checkout] Formas de pagamento
#474 Ajuste CTA da PDP de brinde
#477 Ajustar bolinhas do carrossel da PDP
#482 Lista de pedidos (Minha Conta)

2021-03-12 18:47 UTC, emilioheinz requested changes

2021-03-12 18:47 UTC, emilioheinz commented on src/index.js
> +  )
Não entendi porque do `Promise.all()` porque o retorno do `cards.map` é um array daquele objeto, não um array de async funtions.

2021-03-12 18:47 UTC, emilioheinz commented on src/index.js
> +    let preserveCard = true
```suggestion
    let shouldPreserveCard = true
```

2021-03-12 18:47 UTC, emilioheinz commented on src/index.js
> +  }
Achei um pouco confusos esses returns ai no meio, fica complexo de mudar a função.

2021-03-12 19:17 UTC, opoze commented on src/index.js
> +  )
cards.map return:
```
[
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }, Promise { <pending> },
  Promise { <pending> }
]

2021-03-12 19:19 UTC, RigottiG requested changes

2021-03-12 19:19 UTC, RigottiG commented on src/index.js
> +    return 0
Acho muito complexo dessa maneira, sei que é a mais usada porém é estranha. Consegue testar utilizando o `localeCompare()`

`cardsInfo.sort((a, b) => a.number.localeCompare(b.number))`

acho que seria algo assim.

2021-03-12 19:19 UTC, RigottiG commented on src/index.js
> +}
Está crescendo muito essa função, talvez usar um switch ou object literals.

2021-03-12 19:19 UTC, RigottiG commented on src/index.js
> +  })
Estamos utilizando async/await, não vejo motivo para utilizar o then.

2021-03-12 20:04 UTC, opoze commented on src/index.js
> +  )
É um array de Promises

2021-03-12 20:10 UTC, opoze commented on src/index.js
> +    return 0
localeCompare é para strings: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

2021-03-12 20:12 UTC, opoze commented on src/index.js
> +}
Parece simples, cresceria se tivermos mais filtros, não sei se teremos, talvez dai tenhamos que melhorar os filtros mesmo. Switch/case não funciona aqui.

2021-03-12 20:14 UTC, RigottiG approved these changes

2021-03-15 11:13 UTC, emilioheinz requested changes

2021-03-15 11:13 UTC, emilioheinz commented on src/index.js
> +const Api = new GithubApi(token)
```suggestion
const api = new GithubApi(token)
```

2021-03-15 11:13 UTC, emilioheinz commented on src/index.js
> +const Api = new GithubApi(token)
instancia de classe geralmente não começa com a primeira letra maiuscula.

2021-03-15 11:13 UTC, emilioheinz commented on src/index.js
> +          })
Porque aqui ta sendo usado then? Async await neles.

2021-03-15 11:57 UTC, opoze commented on src/index.js
> +          })
Não está... isso é antigo

2021-03-15 11:59 UTC, emilioheinz approved these changes

2021-03-15 12:00 UTC, merged